# Generated by Django 4.2.7 on 2023-12-06 10:44

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default="dear",
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=3)
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        default="user",
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=3)
                        ],
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        validators=[shop.models.validate_username],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11, validators=[shop.models.validate_phone_number]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=8),
                            shop.models.validate_password,
                        ],
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=1000,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=10)
                        ],
                    ),
                ),
                ("postal_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("price", models.FloatField(default=0)),
                ("description", models.TextField(max_length=500)),
                ("category", models.ManyToManyField(to="shop.category")),
            ],
        ),
    ]
