# Generated by Django 4.2.7 on 2023-12-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_product_quantity_alter_product_price_orderitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "customer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.customer",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("bank_account_number", models.CharField(max_length=20)),
                ("stars", models.PositiveIntegerField(default=0)),
            ],
            bases=("shop.customer",),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="satisfaction_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="shop.seller"
            ),
        ),
    ]
